name: Benchmark

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.2.796'

    - name: Prepare environment
      run: sudo apt-get install -y gnuplot python3-setuptools rlwrap libboost-dev libboost-thread-dev gawk

    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache
      env:
        cache-name: dependencies
      with:
        path: |
          /tmp/dependencies
          node_modules
        key: ${{ runner.os }}-local-${{ env.cache-name }}-${{ hashFiles('DEPENDENCIES') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('package.json') }}

    - name: Install dependencies
      run: make --jobs deps DEPSDIR=/tmp/dependencies

    - name: Lint
      run: make lint

    - name: Benchmark
      run: make benchmark DEPSDIR=/tmp/dependencies
